# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-08 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='to_users',
            new_name='to_user',
        ),
    ]
