# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday_day',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday_month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='hometown_city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='hometown_province',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='head_img',
            field=models.FileField(null=True, upload_to='./uploads/%Y/%m/%d/'),
        ),
    ]
