# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161021_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hometown_area',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
