# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-26 04:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20161021_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='head_img',
            field=models.ImageField(default='storage/img/default_headimg.png', upload_to='storage/img/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='person',
            table='users_person',
        ),
    ]
