# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-01 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20161026_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='user',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
