language: python
sudo: required
cache: pip

python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - python manage.py migrate
  - coverage run --source=blog manage.py test blog/
after_success:
  - coveralls
