# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-30 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160730_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_mun',
        ),
        migrations.AddField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 30, 12, 27, 16, 454650, tzinfo=utc), verbose_name=b'date published'),
            preserve_default=False,
        ),
    ]
