# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-30 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160730_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(verbose_name=b'date replied'),
        ),
    ]
