# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160731_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('pub_date',)},
        ),
        migrations.AddField(
            model_name='blog',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
