# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-18 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160905_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reply_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=40),
        ),
    ]
