# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-18 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160918_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='reply_num',
            field=models.IntegerField(default=0),
        ),
    ]
