# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-18 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20160918_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='latest_reply',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='latest_reply', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
