# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-18 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_latest_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='latest_reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='floor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
