# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-19 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_latest_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='highlighted',
        ),
    ]
