# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-21 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blog_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='floor',
        ),
    ]
