# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_reply_reply_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='latest_reply',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'date latest_reply'),
        ),
    ]
