# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-30 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20161122_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(verbose_name='blog content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=40, verbose_name='blog title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='latest_reply',
            field=models.DateTimeField(auto_now_add=True, verbose_name='latest reply date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='reply_counter',
            field=models.IntegerField(default=0, verbose_name='the count of reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='floor number'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_counter',
            field=models.IntegerField(default=0, verbose_name='the lzl count of reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_text',
            field=models.CharField(max_length=200, verbose_name='reply content'),
        ),
        migrations.AlterField(
            model_name='replyinreply',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='replyinreply',
            name='reply_text',
            field=models.CharField(max_length=200, verbose_name='lzl content'),
        ),
    ]
