# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-01 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='User',
            new_name='user',
        ),
    ]
